return {
  ["Tomorrowland"] = {
    ["BE"] = {
      ["2025"] = {
        ["07-20_2138_FISHER.mp3"],

        ["07-20_2138_FISHER"] = {
          ["01-Chris Lorenzo - Appetite.mp3"],
          ["02-FISHER & AR_CO - Ocean.mp3"],
          ["03-Marlon Hoffstadt aka DJ Daddy Trance - It's That Time (FISHER Remix).mp3"],
          ["04-Fred again.. & Skepta & PlaqueBoyMax - Victory Lap (HILLS Remix).mp3"],
          ["05-FISHER - Stay.mp3"],
          ["06-Piero Pirupa - Let's Jack.mp3"],
          ["07-Nu Aspect - Mind Illusion.mp3"],
          ["08-FISHER ft. Kita Alexander - Atmosphere.mp3"],
          ["09-BIJOU - Mamacita.mp3"],
          ["10-JOSHWA - Work Your Body.mp3"],
          ["11-EdiP - Drgs & Purr.mp3"],
          ["12-FISHER & bbyclose - Blackberries.mp3"],
          ["13-FEZZO - Kids.mp3"],
          ["14-INNDRIVE & Zaark - Take Our Flight.mp3"],
          ["15-Chris Lake & FISHER & Sante Sansone x Gotye ft. Kimbra - Somebody (2024).mp3"],
          ["16-MARTEN HØRGER - No Bite.mp3"],
          ["17-WILL K - Lick It.mp3"],
          ["18-Lady GaGa ft. Colby O'Donis - Just Dance (ACRAZE Remix).mp3"],
          ["19-Anyma & Argy & Son Of Son - Voices In My Head (Chris Lake Remix).mp3"],
          ["20-FISHER - Rain.mp3"],
          ["21-CID & Taylr Renee - Fancy $hit.mp3"],
          ["22-FISHER & Aatig - Take It Off.mp3"],
          ["23-Rafael Cerato & Equinøx - Let It Bang.mp3"],
          ["24-Bob Sinclar ft. Steve Edwards - World, Hold On (Children Of The Sky) (FISHER 2022 Rework).mp3"],
          ["25-Calvin Harris & D.O.D ft. Florence Welch - Sweet Nothing (2025 Edit).mp3"],
          ["26-FISHER - Losing It.mp3"],
          ["27-Marlon Hoffstadt & Coach Harrison - Daddy's In The Club (FISHER Remix).mp3"],
          ["folder.jpg"],
        },
      },
    },
  },
}
